version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env    
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_DB: "webwallet"
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
volumes:
  pgdata: